### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by topisani** [adorbs/meta-otto#1]
Trying it in this form

- [ ] A development build
  - [ ] adds `tools-debug` to `IMAGE_FEATURES` to give `gdb` and `gdbserver` on target
  - [ ] add cross-gdb (not sure how thats done)
- [ ] More work on minimizing dependencies
  - [ ] Try `poky-tiny`
  - [ ] Manual removal of individual features
    - [ ] Can we for example get rid of python on the target? currently it builds both python2 and python3
- [ ] look at having a read only rootfs with a separate otto data partition?
  - [ ] have that data partition auto expand to fill the entire drive on first boot
